# Check the impact of postisrccd rotation

- Sylvie
- 2023/09:27

In [1]:
import numpy as np

In [3]:
arr = np.arange(25)

In [5]:
arr= arr.reshape(5,-1)

In [6]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Apply the rotation as done for postisrccd

In [7]:
rotated_array = arr[::-1,::-1] #rotate the array 180 degrees

In [9]:
rotated_array

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## Apply the different operations performed on the flat

In [10]:
arr_v1 = arr
arr_v2 = np.flipud(arr)
arr_v3 = np.fliplr(arr)
arr_v4 = np.fliplr(np.flipud(arr))

In [11]:
arr_v2

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [12]:
arr_v3

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

In [13]:
arr_v4

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### so the rotation is compatible with version v4 : np.fliplr(np.flipud(arr))